#!/bin/bash

file1=m-oid=1.3.6.1.4.1.18060.0.4.1.2.939.ldif
file2=m-oid=1.3.6.1.4.1.18060.0.4.1.2.940.ldif
file3=m-oid=1.3.6.1.4.1.42.2.27.8.1.32.ldif
file4=m-oid=1.3.6.1.4.1.42.2.27.8.1.33.ldif
file5=m-oid=1.3.6.1.4.1.42.2.27.8.2.1.ldif
file6=m-oid=1.3.6.1.4.1.18060.0.4.1.3.900.ldif

#Check add files
if [ ! -f "$file1" ]; then
  cat > $file1 <<EOF
version: 1
dn: m-oid=1.3.6.1.4.1.18060.0.4.1.2.939,ou=attributeTypes,cn=adsconfig,ou=schema
m-singlevalue: TRUE
m-oid: 1.3.6.1.4.1.18060.0.4.1.2.939
m-syntax: 1.3.6.1.4.1.1466.115.121.1.27
objectclass: top
objectclass: metaTop
objectclass: metaAttributeType
m-name: ads-pwdMinClasses
creatorsname: uid=admin,ou=system
m-equality: integerMatch
m-length: 0
EOF
echo "Added"
fi


if [ ! -f "$file2" ]; then
  cat > $file2 <<EOF
version: 1
dn: m-oid=1.3.6.1.4.1.18060.0.4.1.2.940,ou=attributeTypes,cn=adsconfig,ou=schema
m-singlevalue: TRUE
m-oid: 1.3.6.1.4.1.18060.0.4.1.2.940
m-syntax: 1.3.6.1.4.1.1466.115.121.1.27
objectclass: top
objectclass: metaTop
objectclass: metaAttributeType
m-name: ads-pwdInHistoryDuration
creatorsname: uid=admin,ou=system
m-equality: integerMatch
m-length: 0
EOF
echo "Added"
fi


if [ ! -f "$file3" ]; then
  cat > $file3 <<EOF
version: 1
dn: m-oid=1.3.6.1.4.1.42.2.27.8.1.32,ou=attributeTypes,cn=pwdpolicy,ou=schema
m-singlevalue: TRUE
m-oid: 1.3.6.1.4.1.42.2.27.8.1.32
m-syntax: 1.3.6.1.4.1.1466.115.121.1.27
objectclass: metaTop
objectclass: metaAttributeType
objectclass: top
m-name: pwdMinClasses
creatorsname: uid=admin,ou=system
m-equality: integerMatch
m-length: 0
EOF
echo "Added"
fi


if [ ! -f "$file4" ]; then
  cat > $file4 <<EOF
version: 1
dn: m-oid=1.3.6.1.4.1.42.2.27.8.1.33,ou=attributeTypes,cn=pwdpolicy,ou=schema
m-singlevalue: TRUE
m-oid: 1.3.6.1.4.1.42.2.27.8.1.33
m-syntax: 1.3.6.1.4.1.1466.115.121.1.27
objectclass: metaTop
objectclass: metaAttributeType
objectclass: top
m-name: pwdInHistoryDuration
creatorsname: uid=admin,ou=system
m-equality: integerMatch
m-length: 0
EOF
echo "Added"
fi


#Change files
if [ `grep -c "pwdMinClasses" $file5` -eq '1' ]; then

    echo "Found!"
else
    echo "No Adding config in Apacheds"
    sed -i '$a m-may: pwdMinClasses\' $file5
fi

if [ `grep -c "pwdInHistoryDuration" $file5` -eq '1' ]; then

    echo "Found!"
else
    echo "NO Adding"
    sed -i '$a m-may: pwdInHistoryDuration\' $file5
fi


if [ `grep -c "pwdMinClasses" $file6` -eq '1' ]; then

    echo "Found!"
else
    echo "No Adding config in Apacheds"
    sed -i '$i\m-may: ads-pwdMinClasses\' $file6
fi

if [ `grep -c "pwdInHistoryDuration" $file6` -eq '1' ]; then

    echo "Found!"
else
    echo "NO Adding"
    sed -i '$i\m-may: ads-pwdInHistoryDuration\' $file6
fi

